////////////////////////////////////////////////////////////////////////////////
//
//    Copyright (c) 2022 - 2024.
//    Haixing Hu, Qubit Co. Ltd.
//
//    All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
package ltd.qubit.commons.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * 此注解声明某个属性对应的数据库表字段将被作为该表的主标识符字段。
 *
 * @author 胡海星
 */
@Retention(RUNTIME)
@Target({FIELD})
@Documented
public @interface Identifier {

  /**
   * 表示此ID是否是自动生成的ID。
   *
   * <p>若某个模型的标识符被标记为自动生成的ID，外部程序在调用DAO插入新对象时，无需为新对象设
   * 置ID属性，DAO的具体实现会为其自动生成唯一的ID（或者DAO交由底层数据库来生成这个唯一ID）。
   *
   * <p>此属性默认值为{@code true}。
   *
   * @return 此ID是否是自动生成的ID。
   */
  boolean autoGenerated() default true;

  /**
   * 表示在比较该属性取值时是否忽略大小写。
   *
   * <p>此选项仅对字符串属性有效。默认值为{@code true}。
   *
   * @return 在比较该属性取值时是否忽略大小写。
   */
  boolean ignoreCase() default true;
}
